<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBRUyLy2\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBRUyLy2/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerBRUyLy2.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerBRUyLy2\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerBRUyLy2\appAppKernelProdContainer([
    'container.build_hash' => 'BRUyLy2',
    'container.build_id' => '28f7269b',
    'container.build_time' => 1698073656,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBRUyLy2');
